# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/MSSFAI001/practical_3/practical_3.srcs/sources_1/ip/sine_low/sine_low.xci
# IP: The module: 'sine_low' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/MSSFAI001/practical_3/practical_3.gen/sources_1/ip/sine_low/sine_low_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_low'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/MSSFAI001/practical_3/practical_3.srcs/sources_1/ip/sine_low/sine_low.xci
# IP: The module: 'sine_low' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/MSSFAI001/practical_3/practical_3.gen/sources_1/ip/sine_low/sine_low_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_low'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
